names = ("Ago", "Toast", "Tym", "Peak", "Mountain")
print("Hey " + names[0] + ", thanks for being my friend")
print("Hey " + names[1] + ", thanks for being my friend")
print("Hey " + names[2] + ", thanks for being my friend")
print("Hey " + names[3] + ", thanks for being my friend")
print("Hey " + names[4] + ", thanks for being my friend")